import { Document, Packer, Paragraph, Table, TableCell, TableRow, WidthType, HeadingLevel, TextRun, AlignmentType, BorderStyle } from 'docx';
import { ClaimElement } from './types';

export async function generateWordDocument(
  elements: ClaimElement[],
  patentId: string = 'US123456',
  accusedProduct: string = 'Acme Corp Thermostat'
): Promise<Blob> {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            text: "PATENT INFRINGEMENT CLAIM CHART ANALYSIS",
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 }
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Asserted Patent: ", bold: true }),
              new TextRun({ text: patentId }),
              new TextRun({ text: "   |   Accused Product: ", bold: true }),
              new TextRun({ text: accusedProduct }),
              new TextRun({ text: "   |   Generated by: ", bold: true }),
              new TextRun({ text: "iLumos AI Assistant (Lumenci)" })
            ],
            spacing: { after: 400 }
          }),
          new Table({
            width: {
              size: 100,
              type: WidthType.PERCENTAGE
            },
            rows: [
              // Header Row
              new TableRow({
                tableHeader: true,
                children: [
                  new TableCell({
                    width: { size: 30, type: WidthType.PERCENTAGE },
                    children: [
                      new Paragraph({
                        children: [new TextRun({ text: "Patent Claim Element", bold: true, color: "FFFFFF" })],
                        alignment: AlignmentType.LEFT
                      })
                    ],
                    shading: { fill: "1E293B" }
                  }),
                  new TableCell({
                    width: { size: 30, type: WidthType.PERCENTAGE },
                    children: [
                      new Paragraph({
                        children: [new TextRun({ text: "Accused Product Feature", bold: true, color: "FFFFFF" })],
                        alignment: AlignmentType.LEFT
                      })
                    ],
                    shading: { fill: "1E293B" }
                  }),
                  new TableCell({
                    width: { size: 40, type: WidthType.PERCENTAGE },
                    children: [
                      new Paragraph({
                        children: [new TextRun({ text: "AI Reasoning / Evidence", bold: true, color: "FFFFFF" })],
                        alignment: AlignmentType.LEFT
                      })
                    ],
                    shading: { fill: "1E293B" }
                  })
                ]
              }),
              // Data Rows
              ...elements.map((elem, idx) => {
                const isEven = idx % 2 === 0;
                const bgFill = isEven ? "F8FAFC" : "FFFFFF";
                return new TableRow({
                  children: [
                    new TableCell({
                      width: { size: 30, type: WidthType.PERCENTAGE },
                      children: [
                        new Paragraph({
                          children: [
                            new TextRun({ text: `${elem.claimNumber}: `, bold: true, color: "2563EB" }),
                            new TextRun({ text: elem.elementText })
                          ]
                        })
                      ],
                      shading: { fill: bgFill }
                    }),
                    new TableCell({
                      width: { size: 30, type: WidthType.PERCENTAGE },
                      children: [
                        new Paragraph({
                          children: [new TextRun({ text: elem.accusedFeature })]
                        })
                      ],
                      shading: { fill: bgFill }
                    }),
                    new TableCell({
                      width: { size: 40, type: WidthType.PERCENTAGE },
                      children: [
                        new Paragraph({
                          children: [new TextRun({ text: elem.evidence })]
                        }),
                        new Paragraph({
                          children: [
                            new TextRun({
                              text: `[Confidence: ${(elem.confidenceScore * 100).toFixed(0)}% | Status: ${elem.status.toUpperCase()}]`,
                              italics: true,
                              size: 16,
                              color: elem.status === 'verified' ? '059669' : elem.status === 'weak_evidence' ? 'D97706' : '2563EB'
                            })
                          ],
                          spacing: { before: 100 }
                        })
                      ],
                      shading: { fill: bgFill }
                    })
                  ]
                });
              })
            ]
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: "Confidential - Prepared for Legal Proceedings. Grounded evidence verified via iLumos AI.",
                italics: true,
                size: 18,
                color: "64748B"
              })
            ],
            spacing: { before: 400 },
            alignment: AlignmentType.CENTER
          })
        ]
      }
    ]
  });

  return await Packer.toBlob(doc);
}
